{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "-- MySQL Workbench Forward Engineering\n",
    "\n",
    "SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;\n",
    "SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;\n",
    "SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';\n",
    "\n",
    "-- -----------------------------------------------------\n",
    "-- Schema mydbchurn\n",
    "-- -----------------------------------------------------\n",
    "\n",
    "-- -----------------------------------------------------\n",
    "-- Schema mydbchurn\n",
    "-- -----------------------------------------------------\n",
    "CREATE SCHEMA IF NOT EXISTS `mydbchurn` DEFAULT CHARACTER SET utf8mb3 ;\n",
    "USE `mydbchurn` ;\n",
    "\n",
    "-- -----------------------------------------------------\n",
    "-- Table `mydbchurn`.`status`\n",
    "-- -----------------------------------------------------\n",
    "CREATE TABLE IF NOT EXISTS `mydbchurn`.`status` (\n",
    "  `id` VARCHAR(45) NOT NULL,\n",
    "  `satisfaction_score` INT NOT NULL,\n",
    "  `customer_status` VARCHAR(45) NOT NULL,\n",
    "  `churn_label` VARCHAR(45) NOT NULL,\n",
    "  `churn_value` INT NOT NULL,\n",
    "  `churn_score` INT NOT NULL,\n",
    "  `cltv` INT NOT NULL,\n",
    "  `churn_category` VARCHAR(45) NULL DEFAULT NULL,\n",
    "  `churn_reason` VARCHAR(45) NULL DEFAULT NULL,\n",
    "  PRIMARY KEY (`id`))\n",
    "ENGINE = InnoDB\n",
    "DEFAULT CHARACTER SET = utf8mb3;\n",
    "\n",
    "\n",
    "-- -----------------------------------------------------\n",
    "-- Table `mydbchurn`.`demography`\n",
    "-- -----------------------------------------------------\n",
    "CREATE TABLE IF NOT EXISTS `mydbchurn`.`demography` (\n",
    "  `id` VARCHAR(45) NOT NULL,\n",
    "  `gender` VARCHAR(45) NOT NULL,\n",
    "  `Age` INT NOT NULL,\n",
    "  `married` VARCHAR(45) NOT NULL,\n",
    "  `dependents` VARCHAR(45) NOT NULL,\n",
    "  `number_of_dependents` INT NOT NULL,\n",
    "  `status_id` VARCHAR(45) NOT NULL,\n",
    "  PRIMARY KEY (`id`),\n",
    "  INDEX `fk_demography_status1_idx` (`status_id` ASC) VISIBLE,\n",
    "  CONSTRAINT `fk_demography_status1`\n",
    "    FOREIGN KEY (`status_id`)\n",
    "    REFERENCES `mydbchurn`.`status` (`id`))\n",
    "ENGINE = InnoDB\n",
    "DEFAULT CHARACTER SET = utf8mb3;\n",
    "\n",
    "\n",
    "-- -----------------------------------------------------\n",
    "-- Table `mydbchurn`.`services`\n",
    "-- -----------------------------------------------------\n",
    "CREATE TABLE IF NOT EXISTS `mydbchurn`.`services` (\n",
    "  `id` VARCHAR(45) NOT NULL,\n",
    "  `referred_a_friend` VARCHAR(45) NOT NULL,\n",
    "  `number_of_referrals` INT NOT NULL,\n",
    "  `tenure_in_months` INT NOT NULL,\n",
    "  `offer` VARCHAR(45) NOT NULL,\n",
    "  `phone_service` VARCHAR(45) NOT NULL,\n",
    "  ` avg_monthly_long_distance_charges` FLOAT NOT NULL,\n",
    "  `multiple_lines` VARCHAR(45) NOT NULL,\n",
    "  `internet_service` VARCHAR(45) NOT NULL,\n",
    "  `internet_type` VARCHAR(45) NOT NULL,\n",
    "  `avg_monthly_gb_download` INT NOT NULL,\n",
    "  `online_security` VARCHAR(45) NOT NULL,\n",
    "  `online_backup` VARCHAR(45) NOT NULL,\n",
    "  `device_protection_plan` VARCHAR(45) NOT NULL,\n",
    "  `premium_tech_support` VARCHAR(45) NOT NULL,\n",
    "  `streaming_tv` VARCHAR(45) NOT NULL,\n",
    "  `streaming_movies` VARCHAR(45) NOT NULL,\n",
    "  `streaming_music` VARCHAR(45) NOT NULL,\n",
    "  `unlimited_data` VARCHAR(45) NOT NULL,\n",
    "  `contract` VARCHAR(45) NOT NULL,\n",
    "  `paperless_billing` VARCHAR(45) NOT NULL,\n",
    "  `monthly_charge` FLOAT NOT NULL,\n",
    "  `total_charges` FLOAT NOT NULL,\n",
    "  `total_refunds` FLOAT NOT NULL,\n",
    "  `total_extra_data_charges` INT NOT NULL,\n",
    "  `total_long_distance_cbarges` FLOAT NOT NULL,\n",
    "  `total_revenue` FLOAT NOT NULL,\n",
    "  PRIMARY KEY (`id`))\n",
    "ENGINE = InnoDB\n",
    "DEFAULT CHARACTER SET = utf8mb3;\n",
    "\n",
    "\n",
    "-- -----------------------------------------------------\n",
    "-- Table `mydbchurn`.`demography_has_services`\n",
    "-- -----------------------------------------------------\n",
    "CREATE TABLE IF NOT EXISTS `mydbchurn`.`demography_has_services` (\n",
    "  `demography_id` VARCHAR(45) NOT NULL,\n",
    "  `services_id` VARCHAR(45) NOT NULL,\n",
    "  PRIMARY KEY (`demography_id`, `services_id`),\n",
    "  INDEX `fk_demography_has_services_services1_idx` (`services_id` ASC) VISIBLE,\n",
    "  INDEX `fk_demography_has_services_demography_idx` (`demography_id` ASC) VISIBLE,\n",
    "  CONSTRAINT `fk_demography_has_services_demography`\n",
    "    FOREIGN KEY (`demography_id`)\n",
    "    REFERENCES `mydbchurn`.`demography` (`id`),\n",
    "  CONSTRAINT `fk_demography_has_services_services1`\n",
    "    FOREIGN KEY (`services_id`)\n",
    "    REFERENCES `mydbchurn`.`services` (`id`))\n",
    "ENGINE = InnoDB\n",
    "DEFAULT CHARACTER SET = utf8mb3;\n",
    "\n",
    "\n",
    "-- -----------------------------------------------------\n",
    "-- Table `mydbchurn`.`population`\n",
    "-- -----------------------------------------------------\n",
    "CREATE TABLE IF NOT EXISTS `mydbchurn`.`population` (\n",
    "  `zipcode` INT NOT NULL,\n",
    "  `population` INT NOT NULL,\n",
    "  PRIMARY KEY (`zipcode`))\n",
    "ENGINE = InnoDB\n",
    "DEFAULT CHARACTER SET = utf8mb3;\n",
    "\n",
    "\n",
    "-- -----------------------------------------------------\n",
    "-- Table `mydbchurn`.`localization`\n",
    "-- -----------------------------------------------------\n",
    "CREATE TABLE IF NOT EXISTS `mydbchurn`.`localization` (\n",
    "  `id` VARCHAR(45) NOT NULL,\n",
    "  `city` VARCHAR(45) NOT NULL,\n",
    "  `zipcode` INT NOT NULL,\n",
    "  `population_zipcode` INT NOT NULL,\n",
    "  `demography_id` VARCHAR(45) NOT NULL,\n",
    "  PRIMARY KEY (`id`, `demography_id`),\n",
    "  INDEX `fk_localization_population1_idx` (`population_zipcode` ASC) VISIBLE,\n",
    "  INDEX `fk_localization_demography1_idx` (`demography_id` ASC) VISIBLE,\n",
    "  CONSTRAINT `fk_localization_demography1`\n",
    "    FOREIGN KEY (`demography_id`)\n",
    "    REFERENCES `mydbchurn`.`demography` (`id`),\n",
    "  CONSTRAINT `fk_localization_population1`\n",
    "    FOREIGN KEY (`population_zipcode`)\n",
    "    REFERENCES `mydbchurn`.`population` (`zipcode`))\n",
    "ENGINE = InnoDB\n",
    "DEFAULT CHARACTER SET = utf8mb3;\n",
    "\n",
    "\n",
    "SET SQL_MODE=@OLD_SQL_MODE;\n",
    "SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;\n",
    "SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "iron",
   "language": "python",
   "name": "iron"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
